#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

( cd buoyantSimpleRadiationFoam && wmake )
( cd buoyantBoussinesqSimpleFoam && wmake )


# ----------------------------------------------------------------- end-of-file
