#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

( cd compressible && ./Allwmake )
( cd heatTransfer && ./Allwmake )
( cd incompressible && ./Allwmake )


# ----------------------------------------------------------------- end-of-file
