#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

( cd basic && ./Allwclean )
( cd compressible && ./Allwclean )
( cd heatTransfer && ./Allwclean )
( cd incompressible && ./Allwclean )
( cd DNS && ./Allwclean )
( cd multiphase && ./Allwclean )


# ----------------------------------------------------------------- end-of-file
