#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

( cd compressible && ./Allwclean )
( cd heatTransfer && ./Allwclean )
( cd incompressible && ./Allwclean )


# ----------------------------------------------------------------- end-of-file
