#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

( cd libs && wclean )
( cd icoFoam && wclean )
( cd buoyantSimpleRadiationFoam && wclean )


# ----------------------------------------------------------------- end-of-file
