#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

( cd libs && ./Allwmake )
( cd icoFoam && wmake )
( cd buoyantSimpleRadiationFoam && wmake )
( cd buoyantBoussinesqSimpleFoam && wmake )
( cd simpleFoam && wmake )
( cd icoFoam && wmake )
( cd solvers/compressible/sonicFoam && wmake )



# ----------------------------------------------------------------- end-of-file
