#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

( cd libs && wmake libso )
( cd icoFoam && wmake )
wmake


# ----------------------------------------------------------------- end-of-file
