#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

( cd sonicFoam && wclean )
( cd sonicLiquidFoam && wclean )
( cd rhoPimpleFoam && wclean )
( cd rhoPorousMRFPimpleFoam && wclean )

# ----------------------------------------------------------------- end-of-file
