#!/bin/bash
## VulaSHAKA (Simultaneous Neutronic, Fuel Performance, Heat And Kinetics Analysis)
## Copyright (C) 2009-2010 Pebble Bed Modular Reactor (Pty) Limited (PBMR)
## 
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
## 
## See https://vulashaka.svn.sourceforge.net/svnroot/vulashaka
##
## Author : Alexey PETROV
##


#------------------------------------------------------------------------------
# Source basic functionality
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

. ${TEST_MM_ROOT_DIR}/testing/common/common.sh


#------------------------------------------------------------------------------
# Customize some functions
removeCase ()
{
    echo "Removing '${1}' case from '`pwd`' folder"
    rm -rf $1
}


#------------------------------------------------------------------------------
cleanSolverCase ()
{
   cleanCase `get_source_case $*`

   removeCase `get_reference_case $*`
}


#------------------------------------------------------------------------------
