#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. ${TEST_MM_ROOT_DIR}/testing/common/CleanFunctions

cleanSolverCase
rm -f 0/T

# ----------------------------------------------------------------- end-of-file
