#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. ${TEST_MM_ROOT_DIR}/testing/common/RunFunctions

application=buoyantBoussinesqSimpleFoamMF
echo 
echo "   C++" 
echo 

runApplication blockMesh ""
cp 0/T.org 0/T
runApplication setFields ""
runSolver $application "C"
#./Allclean > /dev/null 2>&1

echo 
echo "   Python                   " 
echo
application="${TEST_MM_ROOT_DIR}/buoyantBoussinesqSimpleFoam/buoyantBoussinesqSimpleFoam.py"
#runApplication blockMesh ""
#cp 0/T.org 0/T
#runApplication setFields ""
#runSolver ${application} "Python"

# ----------------------------------------------------------------- end-of-file
