#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

( cd interFoam && wmake )
( cd interDyMFoam && wmake )
( cd compressibleInterFoam && wmake )

# ----------------------------------------------------------------- end-of-file
