#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

( cd interFoam && wclean )
( cd interDyMFoam && wclean )
( cd compressibleInterFoam && wclean )

# ----------------------------------------------------------------- end-of-file
