#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. ${TEST_MM_ROOT_DIR}/testing/common/RunFunctions

application="icoFoamMF"

echo 
echo "   C++" 
echo 
(cd cavity && runApplication blockMesh "" && runSolver ${application} "C" )
./Allclean > /dev/null 2>&1

echo
echo 
echo "   Python                   " 
echo 
echo
application="${TEST_MM_ROOT_DIR}/icoFoam/icoFoam.py"
(cd cavity && runApplication blockMesh "" && runSolver ${application} "Python" )


# ----------------------------------------------------------------- end-of-file
