from wrappers.src.turbulenceModels.compressible_turbulenceModelHolder import *
from wrappers.src.turbulenceModels.compressible_RASModelHolder import *


RASModelHolder = wrappers.src.turbulenceModels.compressible_RASModelHolder.RASModelHolder
turbulenceModelHolder = wrappers.src.turbulenceModels.compressible_turbulenceModelHolder.turbulenceModelHolder
