#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. ${TEST_MM_ROOT_DIR}/testing/common/RunFunctions

application="buoyantSimpleRadiationFoamMF"

echo 
echo "   C++" 
echo 
runApplication blockMesh ""
runSolver ${application} "C"
#./Allclean > /dev/null 2>&1

echo 
echo "   Python                   " 
echo
application="${TEST_MM_ROOT_DIR}/buoyantSimpleRadiationFoam/buoyantSimpleRadiationFoam.py"
#runApplication blockMesh ""
#runSolver ${application} "Python"


# ----------------------------------------------------------------- end-of-file
