#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

#--------------------------------------------------------------------------------------
# managedFlu - OpenFOAM C++ interactive functionality API
# Copyright (C) 2011- Alexey Petrov
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# See http://sourceforge.net/projects/pythonflu
#
# Author : Alexey PETROV, Andrey Simurzin


#---------------------------------------------------------------------------
( cd managedFlu && wclean libso )
( cd OpenFOAM && wclean libso )
( cd finiteVolume && wclean libso )
( cd dynamicFvMesh && wclean libso )
( cd randomProcesses && wclean libso )
( cd thermophysicalModels/basic && wclean libso )
( cd thermophysicalModels/basicSolidThermo && wclean libso )
( cd thermophysicalModels/radiationModel && wclean libso )
( cd transportModels/incompressible && wclean libso )
( cd transportModels/interfaceProperties && wclean libso )
( cd turbulenceModels/compressible/turbulenceModel && wclean libso )
( cd turbulenceModels/compressible/RAS && wclean libso )
( cd turbulenceModels/incompressible/turbulenceModel && wclean libso )
( cd turbulenceModels/incompressible/RAS && wclean libso )
( cd turbulenceModels/incompressible/LES && wclean libso )
