#ifndef geometricFieldFunctionsMM_H
#define geometricFieldFunctionsMM_H


//---------------------------------------------------------------------------
#include "surfaceScalarFieldHolder.H"


//---------------------------------------------------------------------------
namespace Foam
{

  surfaceScalarFieldHolder mag( const surfaceScalarFieldHolder& );

} // Foam


//---------------------------------------------------------------------------
#endif
