#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

( cd boundaryFoam && wmake )
( cd icoFoam && wmake )
( cd simpleFoam && wmake )


# ----------------------------------------------------------------- end-of-file
