#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

( cd boundaryFoam && wclean )
( cd channelFoam && wclean )
( cd icoFoam && wclean )
( cd nonNewtonianIcoFoam && wclean )
( cd pimpleFoam && wclean )
( cd pimpleDyMFoam && wclean )
( cd pisoFoam && wclean )
( cd simpleFoam && wclean )
( cd shallowWaterFoam && wclean )


# ----------------------------------------------------------------- end-of-file
