#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

( cd laplacianFoam && wmake )
( cd potentialFoam && wmake )
( cd scalarTransportFoam && wmake )

# ----------------------------------------------------------------- end-of-file
