#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

( cd laplacianFoam && wclean )
( cd potentialFoam && wclean )
( cd scalarTransportFoam && wclean )

# ----------------------------------------------------------------- end-of-file
