#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


( cd testMeshDictField && make )
( cd testField && make )
( cd testMatrix && make )

echo "==============================================="
echo " RUN testMeshDictField/testMF.C in \"testField\"" 
( cd testField && testMF )> /dev/null
echo
echo "==============================================="
echo "RUN testField/testUniversalArgs.C in \"testField\""
( cd testField && testUniversalArgs ) > /dev/null
echo
echo "==============================================="
echo   "RUN testMatrix/testMatrix.C in \"testMatrix\""
( cd testMatrix && testMatrix ) > /dev/null
echo
echo "==============================================="




# ----------------------------------------------------------------- end-of-file
