#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. ${TEST_MM_ROOT_DIR}/testing/common/CleanFunctions

( cd decompressionTankFine && cleanSolverCase )
removeCase decompressionTankFine
( cd decompressionTank && cleanSolverCase )

# ----------------------------------------------------------------- end-of-file
